# Generated by Django 5.2.1 on 2025-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='created_at',
            field=models.DateField(),
        ),
    ]
