# Generated by Django 5.1.5 on 2025-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notices_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notices',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='notices',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
