# Generated by Django 5.1.5 on 2025-08-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0002_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='image',
        ),
    ]
