# Generated by Django 5.2.1 on 2025-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
