# Generated by Django 5.1.5 on 2025-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_remove_homework_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode_images/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/'),
        ),
    ]
