# Generated by Django 5.2.1 on 2025-08-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0004_admins_img1_homework_img1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
