# Generated by Django 5.2.1 on 2025-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0004_alter_admins_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('present', models.BooleanField(default=False)),
                ('detail', models.TextField()),
            ],
        ),
    ]
