# Generated by Django 5.1.5 on 2025-08-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0005_delete_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calender',
        ),
    ]
