# Generated by Django 5.1.5 on 2025-08-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0006_delete_calender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
