# Generated by Django 5.1.5 on 2025-08-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0007_delete_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notices',
        ),
    ]
