# Generated by Django 5.2.4 on 2025-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('j_date', models.DateField(default='2004-10-09')),
                ('phone_no', models.IntegerField(default=1234567890)),
                ('total_fees', models.IntegerField(default=10000)),
                ('paid_fees', models.IntegerField(default=5000)),
            ],
        ),
    ]
