# Generated by Django 5.2.1 on 2025-07-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='Students',
        ),
    ]
