# Generated by Django 5.1.5 on 2025-08-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_paid_fees_feehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feehistory',
            old_name='student',
            new_name='student_id',
        ),
    ]
