# Generated by Django 5.2.4 on 2025-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_delete_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fees',
            new_name='paid_fees',
        ),
        migrations.AddField(
            model_name='students',
            name='total_fees',
            field=models.IntegerField(default=10000),
        ),
    ]
