# Generated by Django 5.2.1 on 2025-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_admin_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fees',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='students',
            name='j_date',
            field=models.DateField(default='2004-10-09'),
        ),
        migrations.AddField(
            model_name='students',
            name='phone_no',
            field=models.IntegerField(default=1234567890),
        ),
    ]
