# Generated by Django 5.1.5 on 2025-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_feehistory_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehistory',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
