# Generated by Django 5.2.1 on 2025-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_feehistory_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feehistory',
            name='img1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
