# Generated by Django 5.2.1 on 2025-08-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_feehistory_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feehistory',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='feehistory_images/'),
        ),
    ]
