# Generated by Django 5.1.5 on 2025-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_feehistory_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehistory',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('fail', 'Fail')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
