# Generated by Django 5.2.1 on 2025-08-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_feehistory_method_feehistory_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeHistory',
        ),
    ]
