# Generated by Django 5.2.1 on 2025-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_feehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
