# Generated by Django 5.2.1 on 2025-08-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_students_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='inactive', max_length=10),
        ),
    ]
