# Generated by Django 5.2.1 on 2025-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_students_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='account',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
