# Generated by Django 5.2.1 on 2025-08-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0008_delete_feehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='feehistory_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name_plural': 'Fee Histories',
            },
        ),
    ]
