# Generated by Django 5.2.1 on 2025-08-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feehistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehistory',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text="Admin's reason for approval/rejection", null=True),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('insufficient_proof', 'Insufficient Payment Proof'), ('wrong_amount', 'Wrong Amount'), ('duplicate_payment', 'Duplicate Payment'), ('invalid_receipt', 'Invalid Receipt/Screenshot'), ('other', 'Other (see admin remarks)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
