# Generated by Django 5.1.5 on 2025-09-01 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feehistory_admin_remarks_feehistory_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehistory',
            name='payment_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feehistory',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
